#!/bin/sh

start() {
    echo S99rc start

    cd /usr/share/sensor
    ./main.py &
}

stop() {
    killall main.py
    echo S99rc stop ...
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        sleep 1
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1

esac
