#! /bin/sh

set -e

DESC="reset_ip"
NAME=reset_ip
DAEMON=/bin/$NAME

case "$1" in
  start)
        printf "Starting $DESC: "
	insmod  /lib/modules/gpio_to_irq.ko  && reset_ip  &
        echo "OK"
        ;;
  stop)
        printf "Stopping $DESC: "
        killall  reset_ip
	rmmod gpio_to_irq &
        echo "OK"
        ;;
  restart|force-reload)
        echo "Restarting $DESC: "
        $0 stop
        sleep 1
        $0 start
        echo ""
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
