#!/bin/sh

/webpages/server.py &

echo 22 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio22/direction
echo 0 > /sys/class/gpio/gpio22/value

insmod  /lib/asix.ko

ln -s /dev/ttyS0  /dev/ttyO0
ln -s /dev/ttyS1  /dev/ttyO1
ln -s /dev/ttyS2  /dev/ttyO2
ln -s /dev/ttyS3  /dev/ttyO3

/etc/init.d/S40network restart

if [ -e /on-off.file ]; then
    on-off
fi

ln -s /sys/devices/platform/ocp/44e0b000.i2c/i2c-0/0-0050/eeprom  /dev/eeprom
