#!/bin/sh

#boa &

read_at752_mac &

ln -s /dev/ttyO1  /dev/ttyS1
ln -s /dev/ttyO2  /dev/ttyS2
ln -s /dev/ttyO5  /dev/ttyS3

insmod  /usr/lib/ch341.ko

echo 29 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio29/direction
echo 0 > /sys/class/gpio/gpio29/value
ln -s /sys/class/gpio/gpio29/value /dev/RUN_LED

echo 115 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio115/direction
echo 0 > /sys/class/gpio/gpio115/value
ln -s /sys/class/gpio/gpio115/value /dev/GPIO6

echo 116 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio116/direction
echo 0 > /sys/class/gpio/gpio116/value
ln -s /sys/class/gpio/gpio116/value /dev/GPIO7

sysrunled  &

if [ -e /on-off.file ]; then
    on-off
fi

