#!/bin/sh


start() {
#    ubiattach /dev/ubi_ctrl -m 5
 #   mount -t ubifs ubi1_1 /opt

  #  /opt/init.sh start
}

stop() {
    /opt/init.sh stop
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        sleep 1
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1

esac
