#!/bin/sh

case "$1" in
  start)
    echo "S99rc start: "
    ;;
  stop)
    echo "S99Rrc stop"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

